### ISSUE TITLE
No Audio Response from HA in 2.5.11

### ISSUE THREAD

**Issue by jared-bloomer** [rhasspy/rhasspy-voltron#344]
## Problem
I speak my wake word and call an intent. The intent is sent to MQTT, and HA executes the intent with a `text` parameter in the response to MQTT. The text is NOT spoken on Rhasspy or any satellites. 

### Example Sentence
```
[GetOfficeTemperature]
whats the temperature in [the] office
how (hot | cold) is it
```

### Example HA Intent Script
```
GetOfficeTemperature:
  action:
    - service: mqtt.publish
      data:
        payload_template: '{"sessionId": "{{_intent.sessionId}}", "text" : "The current temperature in the office is {{states("sensor.office_th_office_temperature")}}"}'
        topic: hermes/dialogueManager/endSession
```

### MQTT `hermes/dialogueManager/endSession` message
```
{
  "sessionId": "9dba2fd5-a54d-4978-a5aa-73fcb6e6c8f9",
  "text": "The current temperature in the office is 76.6"
}
```
